### PR TITLE
Math magicians: full website

### PR DESCRIPTION
**Pull request by Fombi-Favour**
In this activity, we:
- Added the react router package.
- Adjusted file hierarchy.
- Completed the project by adding 3 files for navigation.

### CODE REVIEW

**Review by christianbiring1 — APPROVED** [review]
Hi @Fombi-Favour , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
## Highlights
- [ ] Kindly make sure you submit the correct link for your project to be reviewer 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fombi-Favour** [comment]
Hello @christianbiring1
Please I made a mistake on submitting this PR
I submitted this PR on a wrong exercise
Please consider my request 🙏 🙏

**Comment by christianbiring1** [comment]
> Hello @christianbiring1 Please I made a mistake on submitting this PR I submitted this PR on a wrong exercise Please consider my request pray pray

Yeah yeah I just notice it right now, Instead of invalidating I just approved the project

**Review by Ibizugbe — APPROVED** [review]
Hi @Fombi-Favour 👋👋👋, 

approve2


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Linters are passing👍.
- [x] Gitflow is used👍.
- [x] The webpage consists of 3 pages: `Home`, `Calculator`, and `Quote`👍.
- [x] The layout matches the given wireframe👍.
- [x] There is a dedicated route for every page using react router👍.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by enniopo** [comment]
@Fombi-Favour you can now request another code review for your Bookstore: initialize project with components. 
Your previous request has been marked as invalid. Please use a fresh PR. Thank you

**Comment by Ibizugbe** [comment]
Hi @Fombi-Favour 👋🏼👋🏼👋🏼👋🏼, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] The project has met the technical requirements for the milestone👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
